title: Public Policy Advocacy Center
description: Policy Advocacy Toolkit
theme: jekyll-theme-cayman

# Social and Tab Assets
logo: assets/favicon.png
image: assets/thumbnail.jpg

# Automated Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default